"""Create table <name>, <other name>

Revision ID: 8786a75fe2c8
Revises: c4082b0995bb
Create Date: 2023-03-30 12:50:48.648094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8786a75fe2c8'
down_revision = 'c4082b0995bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_column('author_image')

    # ### end Alembic commands ###
