"""added title to update

Revision ID: ea102e95f6e3
Revises: b0620646b9fa
Create Date: 2023-04-09 17:22:07.877623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea102e95f6e3'
down_revision = 'b0620646b9fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('updates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('updates', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
